version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: example-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    networks:
      - elastic

volumes:
  postgres_data:

networks:
  elastic:
    driver: bridge